server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
      routes:
      - id: student
        uri: http://localhost:8081/
        predicates:
        - Path=/student/**
      - id: subject
        uri: http://localhost:8082/
        predicates:
        - Path=/subject/**
      - id: administrator
        uri: http://localhost:8083/
        predicates:
        - Path=/administrator/**  
        - Path=/instructive/**  
        - Path=/period/**  
        - Path=/schedule/**  
