logging:
    level:
        org:
            hibernate:
                SQL: debug
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/dbStudent?false&serverTimezone=UTC
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: create-drop